
-- the password hash is generated by BCrypt Calculator Generator(https://www.dailycred.com/article/bcrypt-calculator)
INSERT INTO user (id, username, password, email, is_smoke_driver, is_music_driver, is_talk_driver, is_smoke_passenger, is_music_passenger, is_talk_passenger) VALUES (1, 'user', '$2a$04$u621Nu4PgrGGd730QPcXEO0b.hrlaDEBNav1LSjt6R/xMbYzYNEa.', 'test@test.com', false, false, false, false, false, false);
INSERT INTO user (id, username, password, email, is_smoke_driver, is_music_driver, is_talk_driver, is_smoke_passenger, is_music_passenger, is_talk_passenger) VALUES (2, 'admin', '$2a$04$u621Nu4PgrGGd730QPcXEO0b.hrlaDEBNav1LSjt6R/xMbYzYNEa.', 'admin@admin.com', false, false, false, false, false, false);

INSERT INTO authority (id, name) VALUES (1, 'ROLE_USER');
INSERT INTO authority (id, name) VALUES (2, 'ROLE_ADMIN');

INSERT INTO user_authority (user_id, authority_id) VALUES (1, 1);
INSERT INTO user_authority (user_id, authority_id) VALUES (2, 1);
INSERT INTO user_authority (user_id, authority_id) VALUES (2, 2);

INSERT INTO location (address, lat, lng) VALUES('6 Rue des Pruniers, 31150 Gratentour, France', 1.437371999999982,43.72221150000001);
INSERT INTO location (address, lat, lng) VALUES('1 Rue du Bois Fleuri, 44200 Nantes, France', -1.5144333000000643, 47.1884331);
INSERT INTO location (address, lat, lng) VALUES('6 Rue des Pruniers, 31150 Gratentour, France', 1.437371999999982,43.72221150000001);
INSERT INTO location (address, lat, lng) VALUES('1 Rue du Bois Fleuri, 44200 Nantes, France', -1.5144333000000643, 47.1884331);
	  
INSERT INTO trajet (driver_id, passengers_id, is_completed, date_departure, max_places, start_location_id, stop_location_id, path_back) VALUES (1, '1', true, CURRENT_TIMESTAMP, 4, 1, 2, false);
INSERT INTO trajet (driver_id, passengers_id, is_completed, date_departure, max_places, start_location_id, stop_location_id, path_back) VALUES (2, '1', true, CURRENT_TIMESTAMP, 4, 3, 4, false);

INSERT INTO contact (trajet_id, receiver_id, sender_id, message, date_sent) VALUES (1, 2, 1, 'bonjour', SYSDATE);
INSERT INTO contact (trajet_id, receiver_id, sender_id, message, date_sent) VALUES (2, 1, 2, 'bonjour', SYSDATE);

